# Generated by Django 6.0.1 on 2026-03-17 08:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
