# Generated by Django 6.0.1 on 2026-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0006_alter_book_author_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
