# Generated by Django 6.0.1 on 2026-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0007_alter_user_book_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='user_book_detail_fine',
            name='total_fine_overdue',
        ),
        migrations.AddField(
            model_name='setting',
            name='borrowing_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_book',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('BORROWING', 'Borrowing'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_book_detail_fine',
            name='late_dates',
            field=models.IntegerField(null=True),
        ),
    ]
