# Generated by Django 6.0.1 on 2026-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0008_remove_book_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
