# Generated by Django 6.0.1 on 2026-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0009_setting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
