# Generated by Django 6.0.1 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0010_user_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
