# Generated by Django 6.0.1 on 2026-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0012_remove_comment_book_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='borrowing_book_date',
            field=models.DateField(null=True),
        ),
    ]
