# Generated by Django 6.0.1 on 2026-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0013_alter_user_book_borrowing_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book_detail_fine',
            name='late_dates',
            field=models.IntegerField(default=0),
        ),
    ]
