# Generated by Django 6.0.1 on 2026-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0015_reservation_updated_at_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CONFIRMED', 'Confirmed'), ('ALREADY', 'Already'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='WAITING', max_length=20),
        ),
    ]
