# Generated by Django 6.0.1 on 2026-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0016_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
