# Generated by Django 6.0.1 on 2026-05-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0017_user_dob_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identity_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
